# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    networks:
      - crawler-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - crawler-network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      # For local Redis use: redis://redis:6379
      # For Upstash use: rediss://default:YOUR_PASSWORD@YOUR_HOST.upstash.io:6379
      - REDIS_URL=rediss://default:ASaKAAIjcDFjZWM5ZDNmOTNhNDM0NWY2YmYxMjc0ZjFkN2RiZmUwZnAxMA@closing-titmouse-9866.upstash.io:6379
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=masterKey
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - meilisearch
    networks:
      - crawler-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  meili_data:

networks:
  crawler-network:
    driver: bridge
    name: crawler-network
