# Generated by datamodel-code-generator 0.83.0 from contracts/openapi.json.
# DO NOT EDIT. Regenerate with `just sdk-generate` (sdks/generate.sh).

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AccountResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    active: bool
    credits_balance: int
    id: str
    name: str
    role: str
    tier: str


class AiExtractionConfig(BaseModel):
    """
    AI extraction configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: bool
    exclude_pages: Optional[list[str]] = None
    include_pages: Optional[list[str]] = None
    prompt: str
    """
    Extraction prompt
    """


class AiFieldDef(BaseModel):
    """
    Field definition for AI schema-based extraction
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    description: str
    field_type: Optional[str] = None
    name: str
    required: Optional[bool] = None


class AiResult(BaseModel):
    """
    AI enrichment results
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    extract: Optional[Any] = None
    summary: Optional[str] = None


class ApiError(BaseModel):
    """
    API error response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    code: str
    details: Optional[Any] = None
    error: str


class ApiKeyResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    active: bool
    created_at: str
    id: str
    last_used_at: Optional[str] = None
    name: str
    prefix: str


class AutoTopupRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    amount: Optional[int] = None
    enabled: bool
    threshold: Optional[int] = None


class BatchScrapeResponse(BaseModel):
    """
    Response of `POST /batch/scrape`
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    job_id: str
    message: str
    status: str
    urls_count: int = Field(..., ge=0)
    """
    Number of URLs accepted
    """


class BillingResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    auto_topup_amount: int
    auto_topup_enabled: bool
    auto_topup_threshold: int
    credits_balance: int
    monthly_spend_limit: Optional[int] = None
    stripe_customer_id: Optional[str] = None
    tier: str


class BulkCrawlError(BaseModel):
    """
    Error for a single config in a bulk submission
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    error: str
    index: int = Field(..., ge=0)


class ConcurrencyConfig(BaseModel):
    """
    Concurrency settings
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    browser_pool_size: Optional[int] = Field(None, ge=0)
    """
    Browser pool size for JS rendering
    """
    dns_concurrency: Optional[int] = Field(None, ge=0)
    """
    DNS resolver concurrency
    """
    max_concurrent_requests: Optional[int] = Field(None, ge=0)
    """
    Maximum concurrent HTTP requests
    """


class ContentBlock(BaseModel):
    """
    A single content block extracted from the document
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    anchor: Optional[str] = None
    """
    Anchor/fragment ID for this block
    """
    content: str
    """
    Block content (text)
    """
    h1: Optional[str] = None
    """
    Heading hierarchy (h1 -> h6)
    """
    h2: Optional[str] = None
    h3: Optional[str] = None
    h4: Optional[str] = None
    h5: Optional[str] = None
    h6: Optional[str] = None
    heading: Optional[str] = None
    """
    Heading text that starts this block
    """
    heading_level: Optional[int] = Field(None, ge=0)
    """
    Heading level (1-6)
    """
    index: int = Field(..., ge=0)
    """
    Block index (0-based)
    """
    markdown: Optional[str] = None
    """
    Block content as Markdown (if available)
    """


class CrawlConfigRecord(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    account_id: str
    config: Any
    created_at: str
    cron_enabled: bool
    cron_expression: Optional[str] = None
    description: Optional[str] = None
    id: str
    last_job_id: Optional[str] = None
    last_run_at: Optional[str] = None
    name: str
    next_run_at: Optional[str] = None
    updated_at: str


class CrawlerType(str, Enum):
    """
    Type of crawler to use
    """

    http = "http"
    browser = "browser"


class CreateApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str


class CreateCrawlResponse(BaseModel):
    """
    Create crawl response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    index_uid: str
    job_id: str
    message: str
    start_urls_count: int = Field(..., ge=0)
    status: str
    warnings: Optional[list[str]] = None
    """
    Non-fatal warnings about config fields that were accepted but cannot
    be honored per-job (worker-level settings). Empty when there are none.
    """


class CreateEngineRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    api_key: Optional[str] = None
    is_default: Optional[bool] = None
    name: str
    url: str


class CreateExtractResponse(BaseModel):
    """
    Response of `POST /extract`
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    job_id: str
    status: str


class CreatedApiKeyResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    key: str
    name: str
    prefix: str


class DiagnosticsStats(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    recent_errors_count: int = Field(..., ge=0)
    total_failures: int = Field(..., ge=0)
    total_requests: int = Field(..., ge=0)
    total_successes: int = Field(..., ge=0)
    tracked_domains: int = Field(..., ge=0)


class DomainInfo(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    avg_response_time_ms: Optional[float] = None
    domain: str
    failed_requests: int = Field(..., ge=0)
    successful_requests: int = Field(..., ge=0)
    total_requests: int = Field(..., ge=0)


class DomainsResponse(BaseModel):
    """
    Domains response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    domains: list[DomainInfo]
    source: str
    total_domains: int = Field(..., ge=0)


class EngineIndex(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    createdAt: str
    primaryKey: Optional[str] = None
    uid: str
    updatedAt: str


class EngineRecord(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    account_id: str
    api_key: str
    created_at: str
    id: str
    is_default: bool
    name: str
    updated_at: str
    url: str


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    code: str
    error: str


class ErrorRecord(BaseModel):
    """
    Error record for tracking
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    domain: str
    error: str
    job_id: str
    retry_count: int = Field(..., ge=0)
    status_code: Optional[int] = Field(None, ge=0)
    timestamp: str
    url: str


class ByDomainItem(RootModel[int]):
    root: int = Field(..., ge=0)


class ByStatus(RootModel[int]):
    root: int = Field(..., ge=0)


class ErrorsResponse(BaseModel):
    """
    Errors response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    by_domain: list[list[Union[str, ByDomainItem]]]
    by_status: dict[str, ByStatus] = Field(..., max_length=0)
    errors: list[ErrorRecord]
    source: str
    total_count: int = Field(..., ge=0)


class ExtractSource(BaseModel):
    """
    One URL an extraction used
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    error: Optional[str] = None
    """
    Why the page could not be fetched
    """
    from_glob: Optional[str] = None
    """
    The glob this URL was resolved from, if any
    """
    success: Optional[bool] = None
    """
    Whether the page was fetched (`null` until it was tried)
    """
    url: str


class ExtractionMode1(str, Enum):
    """
    Extract text content (default)
    """

    text = "text"


class ExtractionMode2(str, Enum):
    """
    Extract inner HTML
    """

    html = "html"


class ExtractionMode3(str, Enum):
    """
    Extract outer HTML (including the element itself)
    """

    outer_html = "outer_html"


class ExtractionMode4(BaseModel):
    """
    Extract a specific attribute value
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    attribute: str
    """
    Extract a specific attribute value
    """


class ExtractionMode5(str, Enum):
    """
    Extract as a list of values (for multiple matches)
    """

    list = "list"


class ExtractionMode6(str, Enum):
    """
    Extract as list of objects with multiple fields
    """

    list_of_objects = "list_of_objects"


class ExtractionMode7(str, Enum):
    """
    Extract first match only (returns null if not found)
    """

    first = "first"


class ExtractionMode8(str, Enum):
    """
    Count matching elements
    """

    count_ = "count"


class ExtractionMode(
    RootModel[Union[ExtractionMode1, ExtractionMode2, ExtractionMode3, ExtractionMode4, ExtractionMode5, ExtractionMode6, ExtractionMode7, ExtractionMode8]]
):
    root: Union[ExtractionMode1, ExtractionMode2, ExtractionMode3, ExtractionMode4, ExtractionMode5, ExtractionMode6, ExtractionMode7, ExtractionMode8]
    """
    How to extract the value from matched elements
    """


class FeatureToggle(BaseModel):
    """
    Simple feature toggle with page filters
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: bool
    """
    Whether the feature is enabled
    """
    exclude_pages: Optional[list[str]] = None
    """
    Exclude pages matching these patterns
    """
    include_pages: Optional[list[str]] = None
    """
    Only apply to pages matching these patterns
    """


class FieldDefinition(BaseModel):
    """
    Field definition for ListOfObjects mode
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    attribute: Optional[str] = None
    """
    Attribute name if mode is Attribute
    """
    mode: Optional[ExtractionMode] = None
    """
    How to extract this field
    """
    selector: str
    """
    CSS selector relative to parent element
    """


class HealthResponse(BaseModel):
    """
    Health check response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    kafka_connected: bool
    status: str
    version: str


class IndexStrategy(str, Enum):
    """
    Indexing strategy for a crawl job.
    """

    update = "update"
    replace_ = "replace"


class JobKind(str, Enum):
    """
    The kind of a job.
    """

    crawl = "crawl"
    batch_scrape = "batch_scrape"
    extract = "extract"


class JobResultError(BaseModel):
    """
    Error of a failed result item
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    code: str
    """
    Machine-readable code (`fetch_error`, `http_error`, `validation_error`, ...)
    """
    message: str


class JobResultItem(BaseModel):
    """
    A single job result, shaped like a `/scrape` response. Fields a job did
    not produce (formats/features it did not request) are omitted.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ai: Optional[dict[str, Any]] = None
    """
    AI enrichment results (`summary`, `extract`)
    """
    block_url: Optional[str] = None
    """
    URL of the block (with its anchor), when the crawl split pages into blocks
    """
    blocks: Optional[list[dict[str, Any]]] = None
    content: Optional[str] = None
    crawled_at: Optional[str] = None
    """
    When the page was crawled (crawl jobs)
    """
    document_id: Optional[str] = None
    """
    Meilisearch document id (crawl jobs)
    """
    error: Optional[JobResultError] = None
    extract: Optional[dict[str, Any]] = None
    """
    Custom selector extraction results
    """
    html: Optional[str] = None
    index: Optional[int] = Field(None, ge=0)
    """
    Position of `source_url` in the submitted `urls` (batch scrape / extract)
    """
    language: Optional[str] = None
    links: Optional[list[str]] = None
    markdown: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    """
    Page metadata (same shape as `ScrapeResponse.metadata`)
    """
    page_block: Optional[int] = Field(None, ge=0)
    """
    Block index within the page, when the crawl split pages into blocks
    """
    raw_html: Optional[str] = None
    schema_: Optional[dict[str, Any]] = Field(None, alias="schema")
    """
    JSON-LD / structured data
    """
    scrape_duration_ms: Optional[int] = Field(None, ge=0)
    source_url: Optional[str] = None
    """
    URL as submitted (batch scrape / extract)
    """
    status_code: Optional[int] = Field(None, ge=0)
    success: bool
    """
    Whether this page was scraped successfully
    """
    url: str
    """
    Page URL (after redirects)
    """
    warning: Optional[str] = None


class JobStatus(str, Enum):
    """
    Crawl job status
    """

    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"
    paused = "paused"


class JobStatusResponse(BaseModel):
    """
    Job status response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    completed_at: Optional[str] = None
    config: Optional[Any] = None
    crawl_rate: float
    documents_sent: int = Field(..., ge=0)
    duration_seconds: Optional[int] = None
    error_message: Optional[str] = None
    errors: int = Field(..., ge=0)
    eta_seconds: Optional[int] = Field(None, ge=0)
    index_uid: str
    job_id: str
    job_type: JobKind
    """
    `crawl`, `batch_scrape` or `extract`
    """
    max_pages: Optional[int] = Field(None, ge=0)
    pages_crawled: int = Field(..., ge=0)
    pages_indexed: int = Field(..., ge=0)
    start_urls: Optional[list[str]] = None
    started_at: Optional[str] = None
    status: JobStatus
    """
    One of `pending`, `running`, `paused`, `completed`, `failed`,
    `cancelled`
    """
    warnings: Optional[list[str]] = None
    """
    Job-level warnings raised by workers while running the job (e.g. a
    requested feature a worker cannot honor), deduplicated. Omitted when
    there are none.
    """


class JobSummary(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    completed: int = Field(..., ge=0)
    failed: int = Field(..., ge=0)
    pending: int = Field(..., ge=0)
    running: int = Field(..., ge=0)
    total: int = Field(..., ge=0)


class LoginRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    email: str
    password: str


class MapLink(BaseModel):
    """
    A discovered link with optional metadata
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    changefreq: Optional[str] = None
    description: Optional[str] = None
    lastmod: Optional[str] = None
    priority: Optional[float] = None
    title: Optional[str] = None
    url: str


class MapRequest(BaseModel):
    """
    Request body for POST /map
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    depth: Optional[int] = Field(None, ge=0)
    """
    How many levels deep to follow links beyond sitemap (default: 0, max: 5)
    """
    get_changefreq: Optional[bool] = None
    """
    Include changefreq from sitemap data (default: true)
    """
    get_description: Optional[bool] = None
    """
    Fetch <meta description> from each page's HTML head (default: true)
    """
    get_lastmod: Optional[bool] = None
    """
    Include lastmod from sitemap data (default: true)
    """
    get_priority: Optional[bool] = None
    """
    Include priority from sitemap data (default: true)
    """
    get_title: Optional[bool] = None
    """
    Fetch <title> from each page's HTML head (default: true)
    """
    limit: Optional[int] = Field(None, ge=0)
    """
    Maximum number of links to return (default: 5000)
    """
    render_js: Optional[bool] = None
    """
    Render JavaScript before extracting metadata (requires Chrome/Chromium)
    """
    search: Optional[str] = None
    """
    Filter results to URLs matching this search term
    """
    sitemap: Optional[bool] = None
    """
    Whether to use sitemaps for discovery (default: true)
    """
    url: str
    """
    Website URL to map
    """


class MapResponse(BaseModel):
    """
    Response for POST /map
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    duration_ms: int = Field(..., ge=0)
    """
    Time taken in milliseconds
    """
    links: list[MapLink]
    success: bool
    total: int = Field(..., ge=0)
    """
    Total number of links discovered
    """


class MeilisearchSettings(BaseModel):
    """
    Meilisearch index settings
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    distinct_attribute: Optional[str] = None
    filterable_attributes: Optional[list[str]] = None
    ranking_rules: Optional[list[str]] = None
    searchable_attributes: Optional[list[str]] = None
    sortable_attributes: Optional[list[str]] = None
    stop_words: Optional[list[str]] = None
    synonyms: Optional[dict[str, list[str]]] = None


class MeilisearchStats(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    available: bool
    url: str


class MessageResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    message: str


class PdfConfig(BaseModel):
    """
    Opt-in configuration for PDF scraping.

    When `enabled = true`, PDFs are fetched (with base64-encoded transport
    through the content worker), parsed for text + metadata, and indexed into
    the same Meilisearch index. All other fields default to conservative values.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: bool
    """
    Whether PDF scraping is enabled.
    """
    extract_links: Optional[bool] = None
    """
    Reserved flag for extracting URLs embedded inside PDF text.
    Currently a no-op; will be wired up in a follow-up issue.
    """
    max_size_mb: Optional[int] = Field(None, ge=0)
    """
    Maximum PDF size in megabytes. PDFs larger than this are rejected.
    When `None`, the global fetcher `max_body_size` applies.
    """


class ProxyRotation(str, Enum):
    """
    Proxy rotation strategy
    """

    round_robin = "round_robin"
    random = "random"
    least_used = "least_used"


class RateLimitConfig(BaseModel):
    """
    Rate limiting configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    default_crawl_delay_ms: Optional[int] = Field(None, ge=0)
    """
    Per-domain delay (ms) used when the domain's robots.txt was fetched
    and sets no `Crawl-delay`, and the job sets neither
    `per_domain_delay_ms` (> 0) nor `requests_per_second` /
    `requests_per_minute`. 0 (default) = no extra delay.
    """
    per_domain_delay_ms: Optional[int] = Field(None, ge=0)
    """
    Minimum delay between requests to same domain (ms)
    """
    requests_per_minute: Optional[int] = Field(None, ge=0)
    """
    Maximum requests per minute (global)
    """
    requests_per_second: Optional[float] = None
    """
    Maximum requests per second (global)
    """
    respect_robots_txt: Optional[bool] = None
    """
    Whether to respect robots.txt
    """


class SchemaFeatureConfig(BaseModel):
    """
    Schema.org extraction settings
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    convert_dates: Optional[bool] = None
    """
    Convert ISO dates to timestamps
    """
    enabled: bool
    exclude_pages: Optional[list[str]] = None
    include_pages: Optional[list[str]] = None
    only_types: Optional[list[str]] = None
    """
    Only extract specific schema types
    """


class SchemaItem(BaseModel):
    """
    A single schema.org item
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    field_type: str = Field(..., alias="@type")
    """
    Schema type (e.g., "Article", "Product", "Organization")
    """


class ScrapeFormat(str, Enum):
    """
    Output formats for scrape
    """

    markdown = "markdown"
    html = "html"
    rawhtml = "rawhtml"
    content = "content"
    links = "links"
    metadata = "metadata"
    screenshot = "screenshot"
    schema = "schema"
    blocks = "blocks"


class ScrapeMetadata(BaseModel):
    """
    Metadata from scraped page
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    author: Optional[str] = None
    canonical_url: Optional[str] = None
    description: Optional[str] = None
    keywords: list[str]
    open_graph: Optional[dict[str, str]] = None
    published_date: Optional[str] = None
    title: Optional[str] = None
    twitter: Optional[dict[str, str]] = None


class SearchRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    filter: Optional[Any] = None
    limit: Optional[int] = Field(None, ge=0)
    offset: Optional[int] = Field(None, ge=0)
    q: str
    sort: Optional[list[str]] = None
    url: str


class SelectorDef(RootModel[Union[str, list[str]]]):
    root: Union[str, list[str]]
    """
    CSS selector definition
    """


class SelectorDefinition1(BaseModel):
    """
    Single CSS selector
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    selector: str


class SelectorDefinition2(BaseModel):
    """
    Multiple CSS selectors (first match wins)
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    selectors: list[str]


class SelectorInput1(BaseModel):
    """
    Single CSS selector
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    selector: str


class SelectorInput2(BaseModel):
    """
    Multiple CSS selectors (first match wins)
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    selectors: list[str]


class SelectorInput(RootModel[Union[SelectorInput1, SelectorInput2]]):
    root: Union[SelectorInput1, SelectorInput2]
    """
    Input selector format
    """


class ServiceStatus(BaseModel):
    """
    Service health status for each component
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    last_seen_secs_ago: Optional[int] = Field(None, ge=0)
    name: str
    status: str


class SignupRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    email: str
    full_name: Optional[str] = None
    password: str


class SitemapConfig(BaseModel):
    """
    Sitemap discovery settings
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: Optional[bool] = True
    """
    Whether to discover and use sitemaps (default: true)
    """
    urls: Optional[list[str]] = None
    """
    Explicit sitemap URLs to use
    """


class SpendLimitRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    monthly_spend_limit: Optional[int] = None


class SystemStatsResponse(BaseModel):
    """
    System stats response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    collected_at: str
    diagnostics: DiagnosticsStats
    jobs: JobSummary
    meilisearch: Optional[MeilisearchStats] = None


class TopupRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    amount: int


class TopupResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    credits_balance: int
    message: str
    transaction_id: str


class TransactionResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    amount: int
    balance_after: int
    created_at: str
    description: Optional[str] = None
    id: str
    type: str


class TransactionsListResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    total: int
    transactions: list[TransactionResponse]


class Transform1(str, Enum):
    """
    Trim whitespace
    """

    trim = "trim"


class Transform2(str, Enum):
    """
    Convert to lowercase
    """

    lowercase = "lowercase"


class Transform3(str, Enum):
    """
    Convert to uppercase
    """

    uppercase = "uppercase"


class Transform4(str, Enum):
    """
    Remove extra whitespace
    """

    normalize_whitespace = "normalize_whitespace"


class Transform5(str, Enum):
    """
    Parse as number (returns null if fails)
    """

    parse_number = "parse_number"


class Transform6(str, Enum):
    """
    Parse as boolean
    """

    parse_boolean = "parse_boolean"


class Transform7(str, Enum):
    """
    Remove HTML tags
    """

    strip_tags = "strip_tags"


class Transform8(BaseModel):
    """
    Take first N characters
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    truncate: int = Field(..., ge=0)
    """
    Take first N characters
    """


class Transform9(BaseModel):
    """
    Split by delimiter
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    split: str
    """
    Split by delimiter
    """


class Transform10(BaseModel):
    """
    Join array with delimiter
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    join: str
    """
    Join array with delimiter
    """


class Replace(BaseModel):
    """
    Replace substring
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    from_: str = Field(..., alias="from")
    to: str


class Transform11(BaseModel):
    """
    Replace substring
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    replace: Replace
    """
    Replace substring
    """


class Transform12(BaseModel):
    """
    Extract with regex
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    regex: str
    """
    Extract with regex
    """


class Transform(
    RootModel[Union[Transform1, Transform2, Transform3, Transform4, Transform5, Transform6, Transform7, Transform8, Transform9, Transform10, Transform11, Transform12]]
):
    root: Union[Transform1, Transform2, Transform3, Transform4, Transform5, Transform6, Transform7, Transform8, Transform9, Transform10, Transform11, Transform12]
    """
    Value transformations
    """


class TriggerResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    config_id: str
    job_id: str
    message: str


class UpdateAccountRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: Optional[str] = None


class UpdateBillingRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    tier: str


class UpdateEngineRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    api_key: Optional[str] = None
    name: Optional[str] = None
    url: Optional[str] = None


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    full_name: Optional[str] = None
    notify_job_emails: Optional[bool] = None


class UrlPatterns(BaseModel):
    """
    URL filtering patterns
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    allowed_domains: Optional[list[str]] = None
    """
    Allowed domains for crawling (strict whitelist)
    When non-empty, only URLs from these exact domains are allowed.
    No subdomain inference or parent domain escapes.
    """
    exclude: Optional[list[str]] = None
    """
    Glob patterns for URLs to exclude
    """
    include: Optional[list[str]] = None
    """
    Glob patterns for URLs to include
    """
    index_only: Optional[list[str]] = None
    """
    Only index URLs matching these patterns (but crawl all)
    """


class UserResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    account: Optional[AccountResponse] = None
    email: str
    email_verified: bool
    full_name: Optional[str] = None
    id: str
    notify_job_emails: bool


class Bearer(BaseModel):
    """
    Bearer token authentication
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    token: str


class WebhookAuth1(BaseModel):
    """
    Bearer token authentication
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    bearer: Bearer
    """
    Bearer token authentication
    """


class Hmac(BaseModel):
    """
    HMAC signature authentication
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    algorithm: Optional[str] = None
    header: Optional[str] = None
    secret: str


class WebhookAuth2(BaseModel):
    """
    HMAC signature authentication
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    hmac: Hmac
    """
    HMAC signature authentication
    """


class Headers(BaseModel):
    """
    Custom headers
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    headers: dict[str, str]


class WebhookAuth3(BaseModel):
    """
    Custom headers
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    headers: Headers
    """
    Custom headers
    """


class WebhookAuth(RootModel[Union[WebhookAuth1, WebhookAuth2, WebhookAuth3]]):
    root: Union[WebhookAuth1, WebhookAuth2, WebhookAuth3]
    """
    Webhook authentication
    """


class WebhookEvent(str, Enum):
    """
    Webhook events
    """

    crawl_started = "crawl_started"
    crawl_completed = "crawl_completed"
    crawl_failed = "crawl_failed"
    progress_update = "progress_update"
    page_crawled = "page_crawled"
    page_indexed = "page_indexed"
    page_error = "page_error"
    batch_sent = "batch_sent"


class AiExtractOptions(BaseModel):
    """
    AI extraction options
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    prompt: Optional[str] = None
    """
    Natural language prompt for extraction
    """
    schema_: Optional[list[AiFieldDef]] = Field(None, alias="schema")
    """
    Schema with field definitions (alternative to prompt)
    """


class AiOptions(BaseModel):
    """
    AI enrichment options for /scrape
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    extract: Optional[AiExtractOptions] = None
    summary: Optional[bool] = None
    """
    Generate a TL;DR summary
    """


class BulkCrawlResponse(BaseModel):
    """
    Bulk crawl response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    errors: list[BulkCrawlError]
    """
    Number of jobs that failed to create
    """
    jobs: list[CreateCrawlResponse]
    """
    Successfully created jobs
    """
    total: int = Field(..., ge=0)
    """
    Total jobs submitted
    """


class CustomSelectorsConfig(BaseModel):
    """
    Custom CSS selector extraction
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    enabled: bool
    exclude_pages: Optional[list[str]] = None
    include_pages: Optional[list[str]] = None
    selectors: dict[str, SelectorDef]
    """
    Map of field name to CSS selector(s)
    """


class ExtractStatusResponse(BaseModel):
    """
    `GET /extract/{id}` response
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    data: Optional[dict[str, Any]] = None
    """
    The extracted data (`null` until the job completed)
    """
    error: Optional[str] = None
    """
    Why the job failed
    """
    job_id: str
    sources: list[ExtractSource]
    """
    URLs used, including those resolved from globs
    """
    status: JobStatus
    """
    `running`, `completed`, `failed`, `cancelled` or `paused`
    """
    warning: Optional[str] = None
    """
    Non-fatal issues: truncated context, failed pages, capped globs, ...
    """


class ExtractedSchema(BaseModel):
    """
    Extracted schema data from an HTML document
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    items: Optional[list[SchemaItem]] = None
    """
    Individual schema items by type
    """
    json_ld: Optional[dict[str, Any]] = None
    """
    All JSON-LD data found (may be array or object)
    """
    json_ld_count: int = Field(..., ge=0)
    """
    Number of JSON-LD scripts found
    """
    microdata: Optional[list[SchemaItem]] = None
    """
    Microdata items
    """
    microdata_count: int = Field(..., ge=0)
    """
    Number of microdata items found
    """


class FeaturesConfig(BaseModel):
    """
    Feature extraction configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ai_extraction: Optional[AiExtractionConfig] = None
    ai_summary: Optional[FeatureToggle] = None
    block_split: Optional[FeatureToggle] = None
    custom_selectors: Optional[CustomSelectorsConfig] = None
    markdown: Optional[FeatureToggle] = None
    metadata: Optional[FeatureToggle] = None
    pdf: Optional[PdfConfig] = None
    schema_: Optional[SchemaFeatureConfig] = Field(None, alias="schema")


class JobResultsResponse(BaseModel):
    """
    One page of a job's results
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    data: list[JobResultItem]
    """
    Results, each shaped like a `/scrape` response
    """
    job_id: str
    job_type: JobKind
    """
    `crawl`, `batch_scrape` or `extract`
    """
    next: Optional[str] = None
    """
    Cursor of the next page; `null` once the job is terminal and every
    result was returned. Always set while the job runs.
    """
    status: JobStatus
    """
    Job status at the time of the read
    """
    total: int = Field(..., ge=0)
    """
    Number of results available so far
    """


class MeilisearchConfig(BaseModel):
    """
    Meilisearch configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    api_key: str
    """
    API key
    """
    batch_size: Optional[int] = Field(None, ge=0)
    """
    Batch size for document indexing
    """
    keep_settings: Optional[bool] = None
    """
    Keep existing settings on re-index
    """
    primary_key: Optional[str] = None
    """
    Primary key field name
    """
    settings: Optional[MeilisearchSettings] = None
    url: str
    """
    Meilisearch URL
    """


class ProxyConfig(BaseModel):
    """
    Proxy configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rotation: Optional[ProxyRotation] = None
    """
    Proxy rotation strategy
    """
    tiered: Optional[list[list[str]]] = None
    """
    Tiered proxy configuration (fallback tiers)
    """
    urls: list[str]
    """
    List of proxy URLs
    """


class ScrapeResponse(BaseModel):
    """
    Response for /scrape endpoint
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ai: Optional[AiResult] = None
    blocks: Optional[list[ContentBlock]] = None
    """
    Content blocks split by headings (if format "blocks" requested)
    """
    content: Optional[str] = None
    """
    Extracted main content text (if requested)
    """
    extract: Optional[dict[str, Any]] = None
    """
    Custom selector extraction results
    """
    html: Optional[str] = None
    """
    Cleaned HTML content (if requested)
    """
    language: Optional[str] = None
    """
    Detected language
    """
    links: Optional[list[str]] = None
    """
    Links found on the page (if requested)
    """
    markdown: Optional[str] = None
    """
    Markdown content (if requested)
    """
    metadata: Optional[ScrapeMetadata] = None
    raw_html: Optional[str] = None
    """
    Raw HTML content (if requested)
    """
    schema_: Optional[ExtractedSchema] = Field(None, alias="schema")
    scrape_duration_ms: int = Field(..., ge=0)
    """
    Time taken to scrape in milliseconds
    """
    status_code: int = Field(..., ge=0)
    """
    HTTP status code
    """
    success: bool
    """
    Whether the scrape was successful
    """
    url: str
    """
    The URL that was scraped (after redirects)
    """
    warning: Optional[str] = None
    """
    Warning message (e.g. "AI requires OPENAI_API_KEY")
    """


class SelectorDefinition3(BaseModel):
    """
    Definition for a single selector extraction
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    attribute: Optional[str] = None
    """
    Attribute name (for Attribute mode)
    """
    default: Optional[dict[str, Any]] = None
    """
    Default value if no match found
    """
    fields: Optional[dict[str, FieldDefinition]] = None
    """
    For ListOfObjects mode: field definitions
    """
    mode: Optional[ExtractionMode] = None
    """
    How to extract the value
    """
    transform: Optional[list[Transform]] = None
    """
    Transform the extracted value (trim, lowercase, etc.)
    """


class SelectorDefinition4(SelectorDefinition1, SelectorDefinition3):
    """
    Definition for a single selector extraction
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )


class SelectorDefinition5(SelectorDefinition2, SelectorDefinition3):
    """
    Definition for a single selector extraction
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )


class SelectorDefinition(RootModel[Union[SelectorDefinition4, SelectorDefinition5]]):
    """
    Definition for a single selector extraction
    """

    root: Union[SelectorDefinition4, SelectorDefinition5]
    """
    Definition for a single selector extraction
    """


class ServiceHealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    services: list[ServiceStatus]


class WebhookConfig(BaseModel):
    """
    Webhook configuration
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    auth: Optional[WebhookAuth] = None
    enabled: Optional[bool] = None
    """
    Whether webhook is enabled
    """
    events: list[WebhookEvent]
    """
    Events to send to this webhook
    """
    name: Optional[str] = None
    """
    Webhook name for identification
    """
    timeout_ms: Optional[int] = Field(None, ge=0)
    """
    Request timeout in milliseconds
    """
    url: str
    """
    Webhook URL
    """


class BatchScrapeRequest(BaseModel):
    """
    Request body for `POST /batch/scrape`. Every field besides `urls`,
    `concurrency` and `webhooks` is a `POST /scrape` option applied to each
    URL (the most common ones are listed; any `/scrape` option is accepted).
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ai: Optional[AiOptions] = None
    concurrency: Optional[int] = Field(None, ge=0)
    """
    URLs scraped at once (default 10, max 25)
    """
    exclude_selectors: Optional[list[str]] = None
    """
    CSS selectors to remove before extraction
    """
    extract: Optional[dict[str, SelectorDefinition]] = None
    """
    Custom CSS selector extraction (field_name -> selector definition)
    """
    formats: Optional[list[ScrapeFormat]] = None
    """
    Formats to return for each URL (default: markdown, content, metadata)
    """
    headers: Optional[dict[str, str]] = None
    """
    Custom request headers
    """
    include_links: Optional[bool] = None
    """
    Include links found on each page
    """
    include_selectors: Optional[list[str]] = None
    """
    CSS selectors to keep (only extract from these)
    """
    only_main_content: Optional[bool] = None
    """
    Only the main content (default true)
    """
    render_js: Optional[bool] = None
    """
    Render JavaScript (requires Chrome/Chromium on the server)
    """
    timeout_ms: Optional[int] = Field(None, ge=0)
    """
    Per-URL timeout in milliseconds (default 30000)
    """
    urls: list[str]
    """
    URLs to scrape (1 to 1000)
    """
    webhooks: Optional[list[WebhookConfig]] = None
    """
    Webhook subscriptions (same as a crawl's `webhooks`): `crawl_started`,
    `page_crawled`, `page_error`, `crawl_completed`, `crawl_failed`
    """


class CrawlConfig(BaseModel):
    """
    Main configuration for a crawl job
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    allowed_domains: Optional[list[str]] = None
    """
    Allowed domains for crawling (if empty, inferred from start_urls)
    When set, only URLs from these exact domains will be crawled.
    This prevents domain explosion (e.g., crawling all Wikipedia languages
    when you only want en.wikipedia.org)
    """
    concurrency: Optional[ConcurrencyConfig] = None
    """
    Concurrency settings
    """
    crawler_type: Optional[CrawlerType] = None
    """
    Crawler type (http or browser)
    """
    features: Optional[FeaturesConfig] = None
    """
    Feature extraction settings
    """
    headers: Optional[dict[str, str]] = None
    """
    Additional HTTP headers
    """
    index_strategy: Optional[IndexStrategy] = None
    """
    Indexing strategy: how documents are written to the target index.
    - `update`: add/update documents in the existing index (default)
    - `replace`: index into a temporary index, then atomically swap on completion

    Also accepts the legacy field name `replace_index` (bool) for backward compatibility.
    """
    index_uid: Optional[str] = None
    """
    Meilisearch index UID (auto-generated from start_urls[0] if empty)
    """
    max_depth: Optional[int] = Field(None, ge=0)
    """
    Maximum crawl depth from start URLs
    """
    max_pages: Optional[int] = Field(None, ge=0)
    """
    Maximum number of pages to crawl
    """
    meilisearch: Optional[MeilisearchConfig] = None
    """
    Meilisearch settings (optional — resolved from account's default engine when empty)
    """
    proxy: Optional[ProxyConfig] = None
    rate_limit: Optional[RateLimitConfig] = None
    """
    Rate limiting settings
    """
    sitemap: Optional[SitemapConfig] = None
    """
    Sitemap configuration
    """
    source: Optional[str] = None
    """
    Source identifier for multi-tenant indexing.
    When set, all documents from this crawl job are tagged with this value,
    enabling per-source filtering and deletion within a shared index.
    Falls back to the domain if not set.
    """
    start_urls: list[str]
    """
    Starting URLs for the crawl
    """
    url_patterns: Optional[UrlPatterns] = None
    """
    URL pattern configuration
    """
    user_agents: Optional[list[str]] = None
    """
    User agents to rotate
    """
    webhooks: Optional[list[WebhookConfig]] = None
    """
    Webhook configurations
    """


class CrawlSyncResponse(JobStatusResponse):
    """
    `POST /crawl/sync` response: the final job status, plus the first page
    of results when `include_results=true`
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    results: Optional[JobResultsResponse] = None
    results_error: Optional[str] = None
    """
    Why the results could not be read (`include_results=true`)
    """


class CreateConfigRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    config: CrawlConfig
    cron_enabled: Optional[bool] = None
    cron_expression: Optional[str] = None
    description: Optional[str] = None
    name: str


class ExtractRequest(BaseModel):
    """
    Request body for `POST /extract`
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    headers: Optional[dict[str, str]] = None
    """
    Custom request headers for the page fetches
    """
    only_main_content: Optional[bool] = None
    """
    Only use each page's main content (default true)
    """
    prompt: Optional[str] = None
    """
    What to extract, in natural language
    """
    render_js: Optional[bool] = None
    """
    Render JavaScript when fetching pages (requires Chrome/Chromium)
    """
    schema_: Optional[dict[str, Any]] = Field(None, alias="schema")
    """
    Expected output: a JSON Schema object, or a list of field
    definitions `[{ "name", "description", "field_type", "required" }]`
    (the `/scrape` `ai.extract.schema` form)
    """
    timeout_ms: Optional[int] = Field(None, ge=0)
    """
    Per-page fetch timeout in milliseconds (default 30000)
    """
    urls: list[str]
    """
    URLs to extract from (max 50 in total after glob resolution). A URL
    containing `*` is a glob resolved from the site's sitemaps and the
    links of its base page: `https://example.com/blog/*`.
    """
    webhooks: Optional[list[WebhookConfig]] = None
    """
    Webhook subscriptions (same as a crawl's `webhooks`)
    """


class ScrapeRequest(BaseModel):
    """
    Request body for /scrape endpoint
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    ai: Optional[AiOptions] = None
    exclude_selectors: Optional[list[str]] = None
    """
    CSS selectors to remove before extraction
    """
    extract: Optional[dict[str, SelectorDefinition]] = None
    """
    Custom CSS selector extraction (field_name -> selector definition)
    """
    formats: Optional[list[ScrapeFormat]] = None
    """
    Formats to return (default: all)
    """
    headers: Optional[dict[str, str]] = None
    """
    Custom headers to send with the request
    """
    include_links: Optional[bool] = None
    """
    Include links found on the page
    """
    include_selectors: Optional[list[str]] = None
    """
    CSS selectors to keep (only extract from these)
    """
    only_main_content: Optional[bool] = None
    """
    Whether to only return the main content (excludes nav, footer, etc.)
    """
    render_js: Optional[bool] = None
    """
    Render JavaScript before extracting content (requires Chrome/Chromium)
    """
    timeout_ms: Optional[int] = Field(None, ge=0)
    """
    Timeout in milliseconds (default: 30000)
    """
    url: str
    """
    URL to scrape
    """


class UpdateConfigRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    config: Optional[CrawlConfig] = None
    cron_enabled: Optional[bool] = None
    cron_expression: Optional[str] = None
    description: Optional[str] = None
    name: Optional[str] = None
