#!/usr/bin/env bash
# Regenerate the SDKs' generated code from contracts/openapi.json.
#
#   sdks/generate.sh                 regenerate both SDKs in place
#   sdks/generate.sh --check         fail (exit 1) if the committed generated
#                                    code is out of date with the spec
#   sdks/generate.sh typescript      only one SDK (typescript | python)
#
# Generators are pinned so the output is deterministic:
#   - TypeScript: openapi-typescript, pinned in sdks/typescript/package.json
#     (+ package-lock.json); installed with `npm ci` if missing.
#   - Python: datamodel-code-generator, pinned below, run through `uvx` on a
#     pinned Python so no global install is needed.
#
# Only the generated files are touched:
#   sdks/typescript/src/generated/schema.ts
#   sdks/python/src/scrapix/_generated/models.py
# The hand-written clients import from them; a spec change that breaks the
# clients shows up in `npm run typecheck` / the Python tests.
set -euo pipefail

DATAMODEL_CODEGEN_VERSION="0.83.0"
DATAMODEL_CODEGEN_PYTHON="3.12"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="$ROOT/contracts/openapi.json"
TS_DIR="$ROOT/sdks/typescript"
PY_DIR="$ROOT/sdks/python"
TS_OUT="src/generated/schema.ts"
PY_OUT="src/scrapix/_generated/models.py"

check=0
targets=()
for arg in "$@"; do
    case "$arg" in
        --check) check=1 ;;
        typescript | python) targets+=("$arg") ;;
        -h | --help)
            sed -n '2,19p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "unknown argument: $arg" >&2
            exit 2
            ;;
    esac
done
[ ${#targets[@]} -eq 0 ] && targets=(typescript python)

gen_typescript() {
    local out="$1"
    if [ ! -x "$TS_DIR/node_modules/.bin/openapi-typescript" ]; then
        (cd "$TS_DIR" && npm ci --no-audit --no-fund --silent)
    fi
    (cd "$TS_DIR" && node_modules/.bin/openapi-typescript "$SPEC" --output "$out" >/dev/null)
}

gen_python() {
    local out="$1"
    command -v uvx >/dev/null || {
        echo "uvx not found: install uv (https://docs.astral.sh/uv/)" >&2
        exit 1
    }
    mkdir -p "$(dirname "$out")"
    uvx --quiet --python "$DATAMODEL_CODEGEN_PYTHON" \
        --from "datamodel-code-generator==$DATAMODEL_CODEGEN_VERSION" \
        datamodel-codegen \
        --input "$SPEC" \
        --input-file-type openapi \
        --output "$out" \
        --output-model-type pydantic_v2.BaseModel \
        --target-python-version 3.10 \
        --no-use-union-operator \
        --use-standard-collections \
        --use-subclass-enum \
        --extra-fields allow \
        --allow-population-by-field-name \
        --use-schema-description \
        --use-field-description \
        --field-constraints \
        --use-double-quotes \
        --formatters builtin \
        --disable-timestamp \
        --custom-file-header "# Generated by datamodel-code-generator $DATAMODEL_CODEGEN_VERSION from contracts/openapi.json.
# DO NOT EDIT. Regenerate with \`just sdk-generate\` (sdks/generate.sh)."
}

status=0
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for target in "${targets[@]}"; do
    case "$target" in
        typescript) dir="$TS_DIR" rel="$TS_OUT" ;;
        python) dir="$PY_DIR" rel="$PY_OUT" ;;
    esac
    if [ "$check" -eq 1 ]; then
        fresh="$tmp/$target/$(basename "$rel")"
        mkdir -p "$(dirname "$fresh")"
        "gen_$target" "$fresh"
        if diff -u "$dir/$rel" "$fresh" >"$tmp/$target.diff" 2>&1; then
            echo "ok: sdks/$target/$rel is up to date"
        else
            echo "STALE: sdks/$target/$rel differs from contracts/openapi.json" >&2
            head -n 60 "$tmp/$target.diff" >&2
            status=1
        fi
    else
        "gen_$target" "$dir/$rel"
        echo "generated sdks/$target/$rel"
    fi
done

if [ "$status" -ne 0 ]; then
    echo >&2
    echo "Generated SDK code is out of date. Run \`just sdk-generate\` and commit the result." >&2
fi
exit "$status"
