app = 'scraper'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  # Redis and MeiliSearch URLs will be set via secrets
  # REDIS_URL = 'redis://...'
  # MEILISEARCH_HOST = 'https://...'
  # MEILISEARCH_API_KEY = '...'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = '10s'
  timeout = '2s'
  grace_period = '5s'
  method = 'GET'
  path = '/health'



[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = 'echo "Deployment starting..."' 