apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapix-api
  namespace: scrapix
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapix-frontier
  namespace: scrapix
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapix-worker-crawler
  namespace: scrapix
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapix-worker-content
  namespace: scrapix
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
