# fly.toml app configuration file
app = "scrapix-proxy"
primary_region = "iad"

[build]

[env]
  PORT = "3000"
  PROXY_PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/proxy-health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Proxy service on port 8080
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80